userextensions/urls.py
from django.urls import path
from userextensions import views
from userextensions.views import ajax
from userextensions.views import action

app_name = 'userextensions'

urlpatterns = [

    # list views
    path('list_recents/', views.ListRecents.as_view(), name='list_recents'),
    path('list_favorites/', views.ListFavorites.as_view(), name='list_favorites'),

    # detail views
    path('detail_user/', views.DetailUser.as_view(), name='detail_user'),

    # create views
    path('add_favorite/', views.AddFavorite.as_view(), name='add_favorite'),

    # update views
    path('set_start_page/', views.SetStartPage.as_view(), name='set_start_page'),

    # delete views
    path('delete_favorite/<int:pk>', views.DeleteFavorite.as_view(), name='delete_favorite'),
    path('delete_recent/<int:pk>', views.DeleteRecent.as_view(), name='delete_recent'),

    # custom views
    path('user_login_redirect/', views.UserLoginRedirect.as_view(), name='user_login_redirect'),
    path('manage_service_accounts/', views.ManageServiceAccounts.as_view(), name='manage_service_accounts'),

    # action views
    path('refresh_api_token', views.RefreshApiToken.as_view(), name='refresh_api_token'),
    path('refresh_srv_acct_token', views.RefreshSrvAcctApiToken.as_view(), name='refresh_srv_acct_token'),
    path('create_srv_account', action.CreateServiceAccount.as_view(), name='create_srv_account'),
    path('delete_srv_account', action.DeleteServiceAccount.as_view(), name='delete_srv_account'),
    path('enable_srv_account', action.EnableServiceAccount.as_view(), name='enable_srv_account'),
    path('disable_srv_account', action.DisableServiceAccount.as_view(), name='disable_srv_account'),

    # ajax views
    path('get_users_per_group', ajax.get_users_per_group, name='get_users_per_group'),

]

userextensions/templates/userextensions/detail/detail_user.html
{% extends base_template|default:"userextensions/userextensions_base.htm" %}
{% load staticfiles %}

{% block content %}
<div class="container-fluid mb-5 animated fadeIn">
    <h1 class="text-primary"><b>User Profile: </b><span class="text-secondary"><small>{{ user.username }}</small></span></h1>
</div>

<div class="container-fluid pl-5 pr-5">

    <!-- user details -->
    <div class="row mb-5 animated fadeIn" style="animation-delay: .25s;">
        <div class="col-sm-12 col-md-3 col-lg-2 mb-3 pl-0">
            <i class="far fa-address-card fa-6x text-primary"></i><br/>
        </div>

        <div class="col-sm-12 col-md-9 col-lg-10">
            <div class="row border-bottom border-secondary p-2">
                <div class="col-sm-3 font-weight-bold text-primary">Is Active: </div>
                <div class="col-sm-9">
                    {% if user.is_active %}
                    <span class="badge badge-pill badge-primary"><i class="fa fa-check fa-fw"></i></span>
                    {% else %}
                    <span class="badge badge-pill badge-danger"><i class="fa fa-times fa-fw"></i></span>
                    {% endif %}
                </div>
            </div>

            <div class="row border-bottom border-secondary p-2">
                <div class="col-sm-3 font-weight-bold text-primary">Is Staff: </div>
                <div class="col-sm-9">
                    {% if user.is_staff %}
                    <span class="badge badge-pill badge-primary"><i class="fa fa-check fa-fw"></i></span>
                    {% else %}
                    <span class="badge badge-pill badge-danger"><i class="fa fa-times fa-fw"></i></span>
                    {% endif %}
                </div>
            </div>

            <div class="row border-bottom border-secondary p-2">
                <div class="col-sm-3 font-weight-bold text-primary">Is Superuser: </div>
                <div class="col-sm-9">
                    {% if user.is_superuser %}
                    <span class="badge badge-pill badge-primary"><i class="fa fa-check fa-fw"></i></span>
                    {% else %}
                    <span class="badge badge-pill badge-danger"><i class="fa fa-times fa-fw"></i></span>
                    {% endif %}
                </div>
            </div>

            <div class="row border-bottom border-secondary p-2">
                <div class="col-sm-3 font-weight-bold text-primary">Date Joined: </div>
                <div class="col-sm-9">{{ user.date_joined }}</div>
            </div>

            <div class="row p-2">
                <div class="col-sm-3 font-weight-bold text-primary">API Token: </div>
                <div class="col-sm-9">
                    {{ token }} &nbsp;&nbsp;
                    <a href="#" class="atmo-link-padding atmo-link-text" title="refresh token"
                       onClick="confirmAction('{% url "userextensions:refresh_api_token" %}', 'Update Token', 'This will delete your API token and create a new one. Do you wish to continue?', 'Continue', 'POST');"
                    role="button" data-toggle="tooltip" data-placement="left">
                    <i class="fas fa-sync-alt"></i>
                    </a>
                </div>
            </div>

        </div>
    </div>

    <!-- user profile -->
    <div class="row mb-5 animated fadeIn" style="animation-delay: .5s;">
        <div class="col-sm-12 col-md-3 col-lg-2 mb-3 pl-0">
            <i class="fas fa-cogs fa-6x text-primary"></i><br/>
        </div>

        <div class="col-sm-12 col-md-9 col-lg-10">
            <div class="row border-bottom border-secondary p-2">
                <div class="col-sm-3 font-weight-bold text-primary">Theme: </div>
                <div class="col-sm-9">{{ user.preference.theme }}</div>
            </div>

            <div class="row border-bottom border-secondary p-2">
                <div class="col-sm-3 font-weight-bold text-primary">Recents Count: </div>
                <div class="col-sm-9">{{ user.preference.recents_count }}</div>
            </div>

            <div class="row border-bottom border-secondary p-2">
                <div class="col-sm-3 font-weight-bold text-primary">Start Page: </div>
                <div class="col-sm-9">{{ user.preference.page_refresh_time }}</div>
            </div>

            <div class="row p-2">
                <div class="col-sm-3 font-weight-bold text-primary">Edit: </div>
                <div class="col-sm-9">
                    <a href="#" class="no-underline" data-toggle="modal" data-target="#modal_{{ form_data_user_preferences.modal_name }}">
                        <i class="fas fa-edit"></i>
                    </a>
                </div>
            </div>

        </div>
    </div>

    <!-- groups -->
    <div class="row mb-5 animated fadeIn" style="animation-delay: .75s;">
        <div class="col-sm-12 col-md-3 col-lg-2 mb-3 pl-0">
            <i class="fas fa-users fa-6x text-primary"></i><br/>
        </div>

        <div class="col-sm-12 col-md-9 col-lg-10">
            <div class="row">
                {% if groups %}
                {% for group in groups %}
                <div class="col-sm-12 col-md-8 col-lg-4">{{ group }}</div>
                {% endfor %}
                {% else %}
                <div>no group memberships found</div>
                {% endif %}
            </div>
        </div>
    </div>

</div>

{% with form_data_user_preferences as form_data %}
{% include 'handyhelpers/generic/generic_modal_form.htm' %}
{% endwith %}

<div class="m-5">&nbsp;</div>
{% include 'handyhelpers/component/modals.htm' %}

{% endblock content %}