userextensions/urls.py
from django.urls import path
from userextensions import views
from userextensions.views import ajax
from userextensions.views import action

app_name = 'userextensions'

urlpatterns = [

    # list views
    path('list_recents/', views.ListRecents.as_view(), name='list_recents'),
    path('list_favorites/', views.ListFavorites.as_view(), name='list_favorites'),

    # detail views
    path('detail_user/', views.DetailUser.as_view(), name='detail_user'),

    # create views
    path('add_favorite/', views.AddFavorite.as_view(), name='add_favorite'),

    # update views
    path('set_start_page/', views.SetStartPage.as_view(), name='set_start_page'),

    # delete views
    path('delete_favorite/<int:pk>', views.DeleteFavorite.as_view(), name='delete_favorite'),
    path('delete_recent/<int:pk>', views.DeleteRecent.as_view(), name='delete_recent'),

    # custom views
    path('user_login_redirect/', views.UserLoginRedirect.as_view(), name='user_login_redirect'),
    path('manage_service_accounts/', views.ManageServiceAccounts.as_view(), name='manage_service_accounts'),

    # action views
    path('refresh_api_token', views.RefreshApiToken.as_view(), name='refresh_api_token'),
    path('refresh_srv_acct_token', views.RefreshSrvAcctApiToken.as_view(), name='refresh_srv_acct_token'),
    path('create_srv_account', action.CreateServiceAccount.as_view(), name='create_srv_account'),
    path('delete_srv_account', action.DeleteServiceAccount.as_view(), name='delete_srv_account'),
    path('enable_srv_account', action.EnableServiceAccount.as_view(), name='enable_srv_account'),
    path('disable_srv_account', action.DisableServiceAccount.as_view(), name='disable_srv_account'),

    # ajax views
    path('get_users_per_group', ajax.get_users_per_group, name='get_users_per_group'),

]

userextensions/templates/userextensions/snippets/user_extensions_nav_menu.htm
{% comment %}
This snippet adds links to for the views provided by django-userexensions and is designed to be used within a
bootstrap navbar.

To use this, add the following in your navbar where appropriate:
    {% include 'snippits/user_theme.htm' %}

{% endcomment %}
{% load userextension_tags %}

<a class="dropdown-item" href="{% url 'userextensions:detail_user' %}"><i class="fa fa-address-card fw mr-3"></i>Profile</a>
<a class="dropdown-item" href="{% url 'userextensions:manage_service_accounts' %}"><i class="fas fa-users-cog fw" style="margin-right: .75em"></i>Service Accounts</a>
<a class="dropdown-item" href="{% url 'userextensions:list_recents' %}"><b class="far fa-clock fw mr-3"></b>Recents</a>
<a class="dropdown-item" href="{% url 'userextensions:list_favorites' %}"><i class="far fa-heart mr-3"></i>Favorites</a>
<div class="dropdown-divider"></div>
<div class="dropdown-item">
    {% is_favorite request as favorite_id %}
    {% if favorite_id %}
        <form name="addFavoriteForm" method="POST" action="{% url 'userextensions:delete_favorite' favorite_id %}">
            {% csrf_token %}
            <input type="hidden" name="name" value="">
            <a href="javascript:document.addFavoriteForm.submit()"><i class="fas fa-heart-broken mr-3"></i></b>Remove Favorite</a>
        </form>
    {% else %}
        <form name="deleteFavoriteForm" method="POST" action="{% url 'userextensions:add_favorite' %}">
            {% csrf_token %}
            <input type="hidden" name="name" value="">
            <a href="javascript:document.deleteFavoriteForm.submit()"><b class="fas fa-heart mr-3"></b>Add Favorite</a>
        </form>
    {% endif %}
</div>
<div class="dropdown-item">
    <form name="startPageForm" method="POST" action="{% url 'userextensions:set_start_page' %}">
        {% csrf_token %}
        <input type="hidden" name="name" value="">
        <a href="javascript:document.startPageForm.submit()"><b class="fas fa-sign-in-alt mr-3"></b>Set start page</a>
    </form>
</div>

userextensions/templates/userextensions/snippets/user_theme.htm
{% comment %}
This snippet allows customizing the theme (css file) as defined per user in the UserPreference model theme field.
Include this snippet within the head tags of your base template:
<head>{% include 'snippits/user_theme.htm' %}</head>
{% endcomment %}

{% get_theme request as user_theme %}
{% if user_theme %}
<link href="{% static user_theme.css_file %}" rel="stylesheet">
{% else %}
<link href="{% static 'default.css' %}" rel="stylesheet">
{% endif %}