userextensions/urls.py
from django.urls import path
from userextensions import views
from userextensions.views import ajax
from userextensions.views import action

app_name = 'userextensions'

urlpatterns = [

    # list views
    path('list_recents/', views.ListRecents.as_view(), name='list_recents'),
    path('list_favorites/', views.ListFavorites.as_view(), name='list_favorites'),

    # detail views
    path('detail_user/', views.DetailUser.as_view(), name='detail_user'),

    # create views
    path('add_favorite/', views.AddFavorite.as_view(), name='add_favorite'),

    # update views
    path('set_start_page/', views.SetStartPage.as_view(), name='set_start_page'),

    # delete views
    path('delete_favorite/<int:pk>', views.DeleteFavorite.as_view(), name='delete_favorite'),
    path('delete_recent/<int:pk>', views.DeleteRecent.as_view(), name='delete_recent'),

    # custom views
    path('user_login_redirect/', views.UserLoginRedirect.as_view(), name='user_login_redirect'),
    path('manage_service_accounts/', views.ManageServiceAccounts.as_view(), name='manage_service_accounts'),

    # action views
    path('refresh_api_token', views.RefreshApiToken.as_view(), name='refresh_api_token'),
    path('refresh_srv_acct_token', views.RefreshSrvAcctApiToken.as_view(), name='refresh_srv_acct_token'),
    path('create_srv_account', action.CreateServiceAccount.as_view(), name='create_srv_account'),
    path('delete_srv_account', action.DeleteServiceAccount.as_view(), name='delete_srv_account'),
    path('enable_srv_account', action.EnableServiceAccount.as_view(), name='enable_srv_account'),
    path('disable_srv_account', action.DisableServiceAccount.as_view(), name='disable_srv_account'),

    # ajax views
    path('get_users_per_group', ajax.get_users_per_group, name='get_users_per_group'),

]

userextensions/templates/userextensions/table/table_favorites.htm
<table class="table table-condensed table-bordered table-striped" data-toggle="table" data-search="true"
       data-flat="true" data-pagination="true" data-show-pagination-switch="true" data-show-columns="true"
       data-show-export="true" data-reorderable-columns="true" data-resizable="false" data-export-types="['excel','csv','txt','sql']">
    <thead>
        <tr>
            <th data-field="name" data-sortable="true">Name</th>
            <th data-field="url" data-sortable="true">URL</th>
            <th data-field="created_at" data-sortable="true">Last Visited</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for row in queryset %}
        <tr>
            <td>{{ row.name }}</td>
            <td><a href="{{ row.url }}">{{ row.url }}</a></td>
            <td>{{ row.updated_at }}</td>

            <!-- actions -->
            <td>
                <a href="#" onClick="confirmAction('{% url "userextensions:delete_favorite" row.pk %}', 'Delete Favorite', 'This favorite will be permanently removed from your list of favorites; do you wish to continue?', 'Continue', 'POST');">
                    <i class="fas fa-trash mr-3"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

userextensions/templates/userextensions/table/table_recents.htm
<table class="table table-condensed table-bordered table-striped" data-toggle="table" data-search="true"
       data-flat="true" data-pagination="true" data-show-pagination-switch="true" data-show-columns="true"
       data-show-export="true" data-reorderable-columns="true" data-resizable="false" data-export-types="['excel','csv','txt','sql']">
    <thead>
        <tr>
            <th data-field="url" data-sortable="true">URL</th>
            <th data-field="created_at" data-sortable="true">Last Visited</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for row in queryset %}
        <tr>
            <td><a href="{{ row.url }}">{{ row.url }}</a></td>
            <td>{{ row.updated_at }}</td>

            <!-- actions -->
            <td>
                <a href="#" onClick="confirmAction('{% url "userextensions:delete_recent" row.pk %}', 'Delete Recent', 'This recent will be permanently removed from your list of recents; do you wish to continue?', 'Continue', 'POST');">
                    <i class="fas fa-trash mr-3"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>